version: '3.7'
volumes:
  postgres_data:

services:
  db:
    container_name: postgres
    build:
      context: .
      dockerfile: dockerization/Dockerfile-db
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}

  backend:
    container_name: file_server
    build:
      context: .
      dockerfile: dockerization/Dockerfile-server
    restart: always
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    entrypoint: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]

  nginx:
    image: nginx:1.22.1
    container_name: nginx
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "8000:80"
    depends_on:
      - backend