version: '3.7'
volumes:
  postgres_data:

services:
  db:
    container_name: postgres
    build:
      context: .
      dockerfile: dockerization/Dockerfile-db
    restart: always
#    volumes:
#      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}

  backend:
    container_name: file_server
    image: file_server
    build:
      context: .
      dockerfile: dockerization/Dockerfile-server
    restart: always
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    volumes:
      - ./src/logs:/code/logs
    depends_on:
      - db
    entrypoint: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]

  nginx:
    image: nginx:1.22.1
    container_name: nginx
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "8000:80"
    depends_on:
      - backend

  logstash:
#      image: docker.elastic.co/logstash/logstash:7.10.2
      image: docker.elastic.co/logstash/logstash:8.7.0
#      image: docker.elastic.co/logstash/logstash:8.6.1
      depends_on:
        - elasticsearch
      environment:
        # Так как сейчас вы хотите запустить logstash без Elasticsearch, необходимо отключить встроенный мониторинг, отправляющий данные в ES
#        XPACK_MONITORING_ENABLED: "false"
        ES_HOST: "elasticsearch:9200"
      ports:
        - "5044:5044/udp"
      volumes:
        - ./deploy/logstash.conf:/config/logstash.conf:ro
      command: logstash -f /config/logstash.conf

  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    environment:
      # Указываем ES запуститься в одном экземпляре
      discovery.type: single-node
    ports:
      - 9200:9200
    volumes:
      - /tmp/esdata:/tmp/elasticsearch/data
    # Обратите внимание: не стоит использовать для ELK тот же ES, который задействован для полнотекстового поиска в вашем сервисе

  kibana:
#    image: docker.elastic.co/kibana/kibana:7.10.2
    image: docker.elastic.co/kibana/kibana:8.7.0
#    image: docker.elastic.co/kibana/kibana:8.6.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    container_name: filebeat
#    image: docker.elastic.co/beats/filebeat:7.3.2
    image: docker.elastic.co/beats/filebeat:8.7.0s
#    image: docker.elastic.co/beats/filebeat:8.6.2
    entrypoint: filebeat -e -strict.perms=false
    user: root
    restart: always
    volumes:
      - ./src/logs:/var/app/log
      - ./deploy/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
#    depends_on:
#      - logstash
#      - elasticsearch
#      - kibana
#    links:
#      - logstash